name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        with:
          neovim: true
          version: stable

      - name: Setup lua
        uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
        with:
          luaVersion: luajit-2.1

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6.1.0

      - name: Setup lua tools
        shell: bash
        run: |
          luarocks install vusted
          luarocks install luacov
          luarocks install luacov-cobertura

      - name: Test with coverage
        run: vusted --coverage test

      - name: Convert coverage file
        run: luacov-cobertura -o coverage.xml

      - name: Run octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
